### ISSUE TITLE
执行voerkai18n extract后报错

### ISSUE THREAD

**Issue by wangdaodao** [zhangfisher/voerka-i18n#12]
开发环境：
win10 64位
node 14.21.3

项目环境：
vue2

![image](https://user-images.githubusercontent.com/2317442/227925496-ed48d4d8-0a12-4a3a-b457-64a1f3f1c16c.png)

报错：
```shell
Extract translate text has occur error from views\infoManage\components\QualificationView.vue:/\<(?<tagName>\w+)(.*?)(?<i18nKey>{attrName}\s*\=\s*)([\"\'']{1})(?<text>.*?)(\4){1}\s*(.*?)(\>|\/\>)/gm. TypeError: content.replaceAll is not a function
    at D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:49:35
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:48:21
    at Array.forEach (<anonymous>)
    at removeComments (D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:46:35)
    at extractTranslateTextUseRegexp (D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:106:15)
    at D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:211:28
    at Array.reduce (<anonymous>)
    at getTranslateTexts (D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:201:26)
    at Transform._transform (D:\Program Files\nvm\v14.21.3\node_modules\@voerkai18n\cli\extract.plugin.js:412:27)
```

看了下`default.json`是空。

**Comment by wangdaodao** [comment]
意见升级到最新版本了，但是发现还是有问题：
![image](https://user-images.githubusercontent.com/2317442/228099262-4da98ded-5052-4294-a2a4-91666d2442b8.png)

**Comment by zhangfisher** [comment]
最新的`@voerkai18/cli 1.0.67`解决了此问题，请尝试
