### ISSUE TITLE
nodejs（eggjs框架）项目执行初始化voerkai18n init命令报错

### ISSUE THREAD

**Issue by vobear** [zhangfisher/voerka-i18n#22]
eggjs项目，执行命令`voerkai18n init` 初始化报错

```
PS E:\nodejs-dev\dataWish_serve\app> voerkai18n init
工程目录：E:\nodejs-dev\dataWish_serve
语言目录：languages
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:429:7)
    at getCurrentPackageJson (C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\utils\index.js:212:32)
    at Object.initializer (C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\cli\init.command.js:87:32)
    at Command.<anonymous> (C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\cli\init.command.js:204:27)
    at Command.listener [as _actionHandler] (C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\cli\node_modules\commander\lib\command.js:482:17)
    at C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\cli\node_modules\commander\lib\command.js:1283:65
    at C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\cli\node_modules\commander\lib\command.js:1174:33
    at async Command.parseAsync (C:\Users\vobea\AppData\Local\Yarn\Data\global\node_modules\@voerkai18n\cli\node_modules\commander\lib\command.js:935:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

![微信截图_20231101133451](https://github.com/zhangfisher/voerka-i18n/assets/45116869/5dbfc642-b697-4322-b445-c7f17d89dbd7)

**Comment by vobear** [comment]
![image](https://github.com/zhangfisher/voerka-i18n/assets/45116869/2687bf7c-d5b3-4aa1-9c97-d76ef9b3c960)

**Comment by zhangfisher** [comment]
可以尝试一下修改语言文件夹位置：

```
// package.json
{
    "voerkai18n":{
        "entry":"i18n"
    }
}
```

[更改语言目录](https://hangfisher.github.io/voerka-i18n/#/zh/guide/advanced/lang-entry-pathl)

**Comment by vobear** [comment]
> 可以尝试一下修改语言文件夹位置：
> 
> ```
> // package.json
> {
> 
>     "voerkai18n":{
>         "entry":"i18n"
>     }
> }
> ```
> 
> [更改语言目录](https://hangfisher.github.io/voerka-i18n/#/zh/guide/advanced/lang-entry-pathl)

尝试了，并不行哦
![image](https://github.com/zhangfisher/voerka-i18n/assets/45116869/663a2808-7393-4a9d-b3b0-1c5942ac4dbb)

**Comment by vobear** [comment]
> 可以尝试一下修改语言文件夹位置：
> 
> ```
> // package.json
> {
> 
>     "voerkai18n":{
>         "entry":"i18n"
>     }
> }
> ```
> 
> [更改语言目录](https://hangfisher.github.io/voerka-i18n/#/zh/guide/advanced/lang-entry-pathl)

另外，请问一下，node接口返回给前端的sql表数据，能不能翻译了，我看了文档描述是不行的。还请大佬帮忙给个实现方案，感谢。

**Comment by vobear** [comment]
我的项目中，voerkai18n init -m cjs还是会报错找不到path...，重新建一个eggjs项目，能正常。尝试无果，最后的可行方式：将其他项目的languages文件夹复制过来，执行voerkai18n extract ==> voerkai18n compile -m cjs 能正常使用。
