### ISSUE TITLE
无效的语言配置，必须提供有效的默认语言和活动语言.

### ISSUE THREAD

**Issue by csq0668** [zhangfisher/voerka-i18n#46]
`Uncaught Error: [VoerkaI18n]无效的语言配置，必须提供有效的默认语言和活动语言.
    at ze.init (scope.ts:95:33)
    at new VoerkaI18nScope (scope.ts:38:13)
    at index.ts:8:15`
请问这个怎么处理

**Comment by zhangfisher** [comment]
要看你是怎么做的才好发现问题吧

可以认真看一下[快速入门](https://zhangfisher.github.io/voerka-i18n/#/zh/guide/intro/get-started)
